sudo: required  
dist: trusty

language: node_js

node_js:
  - stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test:dist:production

after_success:
  - npm run build:dist

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

#this fails for some reason?!
#addons:
  #firefox: latest